#!/usr/bin/env ruby
# frozen_string_literal: true

require 'action_view'
require 'openssl'
require 'optparse'

class DateFormatter
  include ActionView::Helpers::DateHelper

  def initialize(date, colorize: false)
    @date = date
    @colorize = colorize
  end

  def to_s
    s = distance_of_time_in_words_to_now(@date)
    t = if @date < Time.now
          "#{@date} (#{s} ago)"
        else
          "#{@date} (in #{s})"
        end
    @colorize ? colorize(t) : t
  end

  def colorize(subject)
    day = 3600 * 24

    if Time.now + (30 * day) > @date
      "\033[31;1m#{subject}\033[0m"
    elsif Time.now + (365 * day) > @date
      "\033[33;1m#{subject}\033[0m"
    else
      subject
    end
  end
end

class CASerial
  def initialize(filename)
    @filename = filename
  end

  def next
    res = serial = read
    serial += 1
    write(serial)

    res
  end

  private

  def read
    Integer(File.read(@filename), 16)
  end

  def write(value)
    File.write(@filename, format('%04x', value))
  end
end

options = {
  san: nil,
  ssldir: ['/etc/puppetlabs/puppet/ssl', '/var/puppet/ssl'].select { |dir| File.directory?(dir) }.first,
  yes: false
}

OptionParser.new do |opts|
  opts.on('--subject-alternative-name NAMES', 'Change Subject Alternative Name of CA certificate') do |names|
    options[:san] = names.split(',').map { |domain| "DNS:#{domain}" }.join(', ')
  end
  opts.on('--ssldir PATH', 'Path to Puppet ssl directory') do |dir|
    options[:ssldir] = dir
  end
  opts.on('--yes', 'Assume yes to all questions') do
    options[:yes] = true
  end
end.parse!

serial = CASerial.new("#{options[:ssldir]}/ca/serial")

ca_key = OpenSSL::PKey::RSA.new(File.read("#{options[:ssldir]}/ca/ca_key.pem"))

todo_actions = []

if ARGV.empty?
  warn <<~USAGE
    usage: #{$PROGRAM_NAME} certificate...

    #{$PROGRAM_NAME} #{options[:ssldir]}/ca/ca_crt.pem #{options[:ssldir]}/ca/signed/*.pem
  USAGE
  exit 1
end

ARGV.each do |filename|
  if filename =~ %r{^#{options[:ssldir]}/certs}
    puts "Ignoring #{filename} (certificate used by the puppet agent)"
    next
  end

  puts "Processing #{filename}..."
  cert = OpenSSL::X509::Certificate.new(File.read(filename))

  cn = cert.subject.to_a.select { |entry| entry[0] == 'CN' }.map { |entry| entry[1] }[0]

  puts
  puts "      Serial: #{cert.serial}"
  puts "     Subject: #{cert.subject}"
  puts "  Not Before: #{DateFormatter.new(cert.not_before, colorize: false)}"
  puts "   Not After: #{DateFormatter.new(cert.not_after, colorize: true)}"
  puts

  unless options[:yes]
    print 'Renew certificate [yN] '
    r = $stdin.gets
    next unless r =~ /^[yY]/
  end

  cert.serial = serial.next
  cert.not_after += 3600 * 24 * 365 * 5

  managed_san = false
  if cert.extensions.any? { |extension| (extension.oid == 'authorityKeyIdentifier' && extension.value =~ /serial:/) || options[:san] } # rubocop:disable Layout/LineLength
    # We can't just remove / update an extension, so make a copy and recreate
    # them from scratch.

    ef = OpenSSL::X509::ExtensionFactory.new
    ef.subject_certificate = cert
    ef.issuer_certificate = cert

    extensions = cert.extensions.dup
    cert.extensions = []

    extensions.each do |extension|
      if extension.oid == 'authorityKeyIdentifier' && extension.value =~ /serial:/
        # This extension can be of the form "keyid:<hash>" or
        # "<identifier>:<subject>\nserial:<serial>\n", the later features the
        # serial which has to be changed each time, so prefer the former which
        # match what is recommanded in RFC5280 section 4.2.1.1.
        #
        # Ruby will automagically compute and add the missing ":<hash>" part.
        cert.add_extension(ef.create_extension('authorityKeyIdentifier', 'keyid', false))
      elsif extension.oid == 'subjectAltName' && options[:san]
        cert.add_extension(ef.create_extension('subjectAltName', options[:san], false))
        managed_san = true
      else
        cert.add_extension(extension)
      end
    end

    cert.add_extension(ef.create_extension('subjectAltName', options[:san], false)) if options[:san] && !managed_san
  end

  cert.sign(ca_key, OpenSSL::Digest.new('SHA256'))
  File.write(filename, cert.to_s)

  todo_actions << if filename =~ %r{/ca/ca_crt.pem$}
                    'Remove "${ssldir}/certs/ca.pem" on all nodes'
                  else
                    "Remove \"${ssldir}/certs/#{cn}.pem\" on node #{cn}"
                  end
end

unless todo_actions.empty?
  puts
  puts 'The following actions must be done:'
  todo_actions.each do |action|
    puts "  - #{action}"
  end
end
